plugin:
  name: easydb-editor-field-visibility
  version: 1.0
  url: https://www.gbv.de
  displayname:
    de-DE: Feldauswahl auf Basis des Wertes eines anderen Feldes
    en-US: Field selection based on the value of another field
  info:
    de-DE: Custom Mask Splitter to show / hide fields in Editor, depending on other fields.
    en-US: Custom Mask Splitter to show / hide fields in Editor, depending on other fields.
  server:
    api-version:
      require: 1
  webfrontend:
    url: easydb-editor-field-visibility.js
    l10n: l10n/
